### ISSUE TITLE
PlateHole.m

### ISSUE THREAD

**Issue by Batmanabcdefg** [canitesc/IGAPack#1]
If I firstly run PlateHole.m test, I get the following error infos.

_Undefined function 'init2DGeometryGIFTMP' for input arguments of
type 'char'.
Error in PlateHole (line 35)
GIFTmesh = init2DGeometryGIFTMP('plate_hole');_ 
Best

**Comment by canitesc** [comment]
The function init2DGeometryGIFTMP.m is in the ./ExampleData directory. Make sure that is in your path.

**Comment by Batmanabcdefg** [comment]
1.  init2DGeometryGIFTMP.m is in folder ExampleData
2.  ich have checked the new path using "path", it shows me that I have added this folder.
I use Matlab 2017/ Matlab 2014.

But,if I firstly run PlateHoleC1.m, PlateHoleC1.m works
Then ->PlateHole.m. PlateHole.m is now working

**Comment by Batmanabcdefg** [comment]
%restoredefaultpath --> solves this problem.
